# This workflow will build a Java project with Ant
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-ant

name: Java do modolo

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  compilar:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Build with Ant
      run: |
        cd src
        javac -cp . Main.java
    - name: Rodando o código
      run: |
        cd src
        java -cp . Main
        
    - uses: mr-smithers-excellent/docker-build-push@v6
      name: Deploy Docker image
      with:
          image: mirellamiyakawa/maven_aula
          tags: 1.0
          registry: docker.io
          dockerfile: dockerfile
          username: mirellamiyakawa
          password: ${{ secrets.DOCKER_PASSWORD }}
